workflows:
  ios-html-app:
    name: Build iOS IPA from HTML
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 18
    scripts:
      - name: Build Webview App with Cordova
        script: |
          npm install -g cordova
          cordova create myapp com.haiky.app HaikyApp
          rm -rf myapp/www/*
          rsync -av --exclude='myapp' --exclude='.git' --exclude='codemagic.yaml' ./ myapp/www/
          cd myapp
          cordova platform add ios
          xcodebuild -workspace platforms/ios/HaikyApp.xcworkspace -scheme HaikyApp -sdk iphoneos -configuration Release archive -archivePath $HOME/build/App.xcarchive CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
          mkdir -p $HOME/build/Payload
          cp -r $HOME/build/App.xcarchive/Products/Applications/HaikyApp.app $HOME/build/Payload/
          cd $HOME/build
          zip -r HaikyApp.ipa Payload
    artifacts:
      - $HOME/build/*.ipa
